#spring:
#  datasource:
#    url: jdbc:mysql://39.106.60.85:3306/certification?nullCatalogMeansCurrent=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ENC(fOr/nEECHs08yfJrbdEF5Q==)
#    password: ENC(282KiBcYygZ1KgBzEN5ydA==)
#  cloud:
#    nacos:
#      discovery:
#        metadata:
#          server: ${spring.application.name}
#          Description: 证件信息业务-获取证件状态信息的DEMO
#
#server:
#  port: 8085
#
#jasypt:
#  encryptor:
#    password: capinfo
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#server:
#  servlet:
#    context-path: /CertificationService