spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      # 就是hibernate.hbm2ddl.auto,具体说明可以看README
      ddl-auto: update
      # 通过方法名解析sql的策略,具体说明可以看README, org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    prefix:
      classpath: /templates
    encoding: UTF-8
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露所有节点
  endpoint:
    health:
      show-details: always #显示详细信息


logging:
  file: user-service.log #添加开启admin的日志监控
feign:
  sentinel:
    enabled: true

provider-url-eureka: http://localhost:8201
