spring:
  profiles:
    active: dev
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.20.21.245:1521/orcl
    username: micro_service
    password: zlzy123
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000  # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*' #暴露所有节点
  endpoint:
    health:
      show-details: always #显示详细信息

logging:
  file: logs/card-info-service.log #添加开启admin的日志监控
feign:
  sentinel:
    enabled: true
